import type { Metadata } from "next";
import "../globals.css";
export const metadata: Metadata = {
  title: "F8",
  description: "Generated by create next app",
  icons: "https://fullstack.edu.vn/favicon/favicon_32x32.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>{children}</div>;
}
