import Header from "@/components/admin/Header";
import Sidebar from "@/components/admin/Slidebar";

export const metadata = {
  title: "Learning",
  description: "Generated by Next.js",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="grid grid-cols-6 ">
        <Sidebar />
        <div className="col-span-5">
          <Header />
          <div className="pt-[7rem] bg-[#fefcfb] h-[100vh] overflow-y-scroll scrollbar-custom">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
