import Header from "@/layouts/CourseLearning/header";
export const metadata = {
  title: "Learning",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      {children}
    </div>
  );
}
