import Header from "@/layouts/CourseLearning/header";
import "./layout.css";
export const metadata = {
  title: "Learning",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
