import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/common/Header";
import ProviderWrap from "@/redux/middleware/Provider.wrapper";
import SnackbarProviderConfig from "@/lib/Provider/SnackbarProviderConfig";
import Slider from "@/components/common/Slider/page";
import { MyProvider } from "@/hook/context";
import Footer from "@/components/common/Footer/page";
import Head from "next/head";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "F8",
  description: "Generated by create next app",
  icons: "https://fullstack.edu.vn/favicon/favicon_32x32.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <ProviderWrap>
          <MyProvider>
            <SnackbarProviderConfig>
              <main>{children}</main>
            </SnackbarProviderConfig>
          </MyProvider>
        </ProviderWrap>
      </body>
    </html>
  );
}
