import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/common/Header";
import ProviderWrap from "@/redux/middleware/Provider.wrapper";
import SnackbarProviderConfig from "@/lib/Provider/SnackbarProviderConfig";
export const metadata: Metadata = {
  title: "F8",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderWrap>
          <SnackbarProviderConfig>
            <Header />
            {children}
          </SnackbarProviderConfig>
        </ProviderWrap>
      </body>
    </html>
  );
}
