import Slider from '@/components/client/Slider/page';
import Footer from '@/layout/mainLayout/Footer/page';
import Header from '@/layout/mainLayout/Header';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'F8',
  description: 'Generated by create next app',
  icons: 'https://fullstack.edu.vn/favicon/favicon_32x32.png',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <div className="flex pt-[9rem]">
        <Slider />
        <div className="flex-1 ">{children}</div>
      </div>
      <Footer />
    </div>
  );
}
